version: '3'

vars:
  BUILD_DIR: build
  PROJECT_NAME: pysrt

tasks:
  build:
    desc: Build the project (runs test and lint first)
    deps: [test, lint]
    cmds:
      - task: build-python

  build-ci:
    desc: Build for CI/CD (tests and lint run separately)
    cmds:
      - task: build-python

  build-python:
    desc: Build Python package artifacts
    silent: true
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - uv build --wheel --sdist --out-dir {{.BUILD_DIR}} --quiet

  test:
    desc: Run tests
    silent: true
    cmds:
      - uv run python -m pytest --ignore=llm-shared -q -p no:warnings

  test-ci:
    desc: Run tests with coverage for CI
    cmds:
      - uv run python -m pytest --ignore=llm-shared --cov=pysrt --cov-report=xml --cov-report=term

  lint:
    desc: Run linters and formatters with auto-fix
    silent: true
    cmds:
      - uv run ruff check . --exclude llm-shared --quiet --fix
      - uv run ruff format . --exclude llm-shared --quiet
      - uv run mypy pysrt --no-error-summary

  lint-check:
    desc: Check linting without auto-fix (for CI)
    cmds:
      - uv run ruff check . --exclude llm-shared
      - uv run ruff format . --exclude llm-shared --check
      - uv run mypy pysrt

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf dist
      - rm -rf *.egg-info
      - rm -rf .pytest_cache
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - rm -rf .coverage
      - rm -rf coverage.xml
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true

  install:
    desc: Install dependencies
    cmds:
      - uv sync --extra dev
